version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /var/dynamodb/
    ports:
      - "8000:8000"
    volumes:
      - ./shared/dynamodb:/var/dynamodb

  dev:
    restart: always
    env_file: .env
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/project
    links:
      - dynamodb
